final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homepage_view
from .views import contact_view
from django.conf import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view),
    path('contact/', contact_view),
    path('users/', include('users.urls')),
    path('products/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# this is the route that specify when this url is accessed- where to go to find the file for example
#     contact view which is gonna be a render of either an html, a redirect.
# the url pattern must be present here even though in users we're bringing it here because django's way of reading
# starts with this directory of urls.py

users/urls.py
# this includes the urls
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import register_view

app_name='users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html')),
    path('', include('django.contrib.auth.urls')),
    path('register/', register_view, name='register'),
]

users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from utils.constants import BILLING_ADDRESS, SHIPPING_ADDRESS
from final_project.models import CustomModel

AuthUserModel = get_user_model()
'''This represents the user models, user model default from django added in a variable'''

# Create your models here - ORM converting class objects into django columns

class Address(CustomModel):
    user = models.ForeignKey(AuthUserModel, on_delete=models.CASCADE)
    street = models.CharField(max_length=255, null=False)
    city = models.CharField(max_length=255, null=False)
    country = models.CharField(max_length=255, null=False)

    class Types(models.IntegerChoices):
        SHIPPING = SHIPPING_ADDRESS
        BILLING = BILLING_ADDRESS
    type = models.IntegerField(choices=Types.choices, null=False, default=SHIPPING_ADDRESS)

users/forms.py
from django import forms

class RegisterForm(forms.Form):
    first_name = forms.CharField(label="First name", max_length=255, required=True)
    last_name = forms.CharField(label='Last name', max_length=255, required=True)
    email = forms.EmailField(label='Email', max_length=255, required=True)
    password = forms.CharField(label="Password",widget=forms.PasswordInput, required=True)
    password_confirmation = forms.CharField(label='Password confirmation', widget=forms.PasswordInput, required=True)

    def clean_email(self):
        email=self.cleaned_data.get("email")

        try:
            AuthUser.object.get(email=email)
            except
        AuthUser.DoesNotExist:

        if user:
            raise forms.ValidationError("Email is already taken")
        return email





        label='Password',
        widget=forms.PasswordInput,
        required=True,
        # help_text=password_validators_help_text_html()
    )

users/views.py
from django.shortcuts import render
from users.forms import RegisterForm


def register_view(request):
    if request.method == 'GET':
        form = RegisterForm()
    else:
        form = RegisterForm(request.POST)

    return render(request,
                  'users/register.html',
                  {
                      'form': form
                  })

users/templates/users/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'users:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

<!--{# Assumes you setup the password_reset view in your URLconf #}-->


{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% block content %}

    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        <div>
            <label>First name </label>
            <input name="first_name" type ="'text" />

        </div>
        <div>
            <label> Label name </label>
            <input name="last_name" type ="text"/>
        </div>
        <div>
            <label> Email</label>
            <input name="email" type= "email" />
        </div>
        <div>
            <label> Password </label>
            <input name="password" type="password"/>
        </div>
        <div>
            <label> Password confirmation </label>
            <input name ="password_confirmation" type="password" />
        </div>
            <input type="submit" value ="Register" />
        </div>

</form>
{% endblock %}